import tempfile
from pathlib import Path

from gate.checks.integrity import check_integrity, parse_requirements_hashes


# ── check_integrity ───────────────────────────────────────────────────────────

def test_matching_hashes_pass():
    h = "sha512-abc123"
    result = check_integrity(h, h)
    assert result["ok"] is True
    assert not result.get("skipped")


def test_mismatched_hashes_fail():
    result = check_integrity("sha512-aaa", "sha512-bbb")
    assert result["ok"] is False
    assert "tampered" in result["message"]


def test_empty_local_skips():
    result = check_integrity("", "sha512-abc")
    assert result["ok"] is True
    assert result["skipped"] is True


def test_empty_remote_skips():
    result = check_integrity("sha512-abc", "")
    assert result["ok"] is True
    assert result["skipped"] is True


def test_whitespace_is_stripped():
    result = check_integrity("sha512-abc  ", "  sha512-abc")
    assert result["ok"] is True


def test_pypi_sha256_format():
    h = "sha256:ae72a32d69f2571a7d0c1f0a3e9ef7c7e2a2d1b"
    result = check_integrity(h, h)
    assert result["ok"] is True


# ── parse_requirements_hashes ─────────────────────────────────────────────────

REQUIREMENTS_WITH_HASHES = """\
# generated by pip-compile
requests==2.28.0 \\
    --hash=sha256:ae72a32d69f2571a7d0c1f0a3e9ef7c7e2a2d1b3456789abcdef0123456789ab
urllib3==1.26.12 \\
    --hash=sha256:3fa96cf423e6987997fc326ae8df396db2a8b7c667747d47ddd8ecba91f4a74e
# a comment line
flask==2.0.0
"""


def test_parses_hashes_correctly():
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write(REQUIREMENTS_WITH_HASHES)
        path = Path(f.name)

    try:
        result = parse_requirements_hashes(path)
        assert "requests" in result
        assert result["requests"]["2.28.0"].startswith("sha256:")
        assert "urllib3" in result
        assert result["urllib3"]["1.26.12"].startswith("sha256:")
    finally:
        path.unlink()


def test_skips_packages_without_hashes():
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write(REQUIREMENTS_WITH_HASHES)
        path = Path(f.name)

    try:
        result = parse_requirements_hashes(path)
        assert "flask" not in result
    finally:
        path.unlink()


def test_empty_file_returns_empty_dict():
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write("")
        path = Path(f.name)

    try:
        result = parse_requirements_hashes(path)
        assert result == {}
    finally:
        path.unlink()


def test_package_name_lowercased():
    content = "Requests==2.28.0 --hash=sha256:abc123def456\n"
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write(content)
        path = Path(f.name)

    try:
        result = parse_requirements_hashes(path)
        assert "requests" in result
        assert "Requests" not in result
    finally:
        path.unlink()
